name = "inconigto-mode"
main = "_worker.js"
compatibility_date = "2023-05-26"
workers_dev = true
routes = [
  { pattern = "inconigto-mode.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "support.zoom.us.inconigto-mode.web.id", custom_domain = true },  
  { pattern = "cache.netflix.com.inconigto-mode.web.id", custom_domain = true },
[vars]
